(lang dune 3.24)

(name data_structures)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license AFL-1.0)

(documentation https://url/to/documentation)

(package
 (name data_structures)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml
  (alcotest :with-test))
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
